name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 取出原始碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 登入 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ 建立並推送 image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tony560/my-nuxt3-app:latest
