name: Build, Push and Deploy Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 取出原始碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 登入 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build 並 push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            tony560/my-nuxt3-app:latest
            tony560/my-nuxt3-app:${{ github.sha }}

      # 4️⃣ 部署到 Mac 本機（假設 docker-compose.yml 在專案根目錄）
      - name: Pull and restart container
        run: |
          docker pull tony560/my-nuxt3-app:latest
          docker compose down
          docker compose up -d
